name: epub_package
description: A new Flutter package project.
version: 0.0.3-beta4
author: eGust<egustc@gmail.com>
homepage: https://github.com/eGust/epub-package.dart

environment:
  sdk: ">=2.18.0-dev.68.0 <3.0.0"

dependencies: 
  html: ^0.15.0
  mime: ^1.0.2
  path: ^1.8.2
  xml: ^6.1.0

dev_dependencies:
  test: ^1.16.0
